#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/s/sqlite3/libsqlite3-0_3.40.1-2+deb12u2_i386.deb"
file_size=907712
file_md5=b2a8638b4bb180fbaf394076a64b5d16
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libsqlite3.so.0* "$target"/lib32/ || Die "Failed copying 32-bit SQLite."
}
