#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/libx/libxml2/libxml2_2.9.14+dfsg-1.3~deb12u6_i386.deb"
file_size=722380
file_md5=297ef1c88f2be03f44f3b69186af9f7c
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libxml2.so.2* "$target"/lib32/ || Die "Failed copying 32-bit libxml2."
}
