#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/v/v4l-utils/libv4l-0_1.22.1-5+b2_i386.deb"
file_size=108936
file_md5=5bd7db1e696e8cb22f8fb9897103677b
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libv4l2.so.0* "$target"/lib32/ || Die "Failed copying 32-bit v4l2."
    cp -a usr/lib/i386-linux-gnu/libv4l/v4l2convert.so "$target"/lib32/ || Die "Failed copying 32-bit v4l2convert."
}
