#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/g/gcc-12/libstdc++6_12.2.0-14+deb12u1_i386.deb"
file_size=661256
file_md5=17c08eb1d01b075268c7dd5d113cc221
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libstdc++.so.6* "$target"/lib32/ || Die "Failed copying 32-bit libstdc++."
}
