#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/a/alsa-lib/libasound2_1.2.8-1+b1_i386.deb"
file_size=388148
file_md5=85021f450785ffeb111d3506ccf09316
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libasound.so.2* "$target"/lib32/ || Die "Failed copying 32-bit ALSA."
}
