#!/bin/bash

# 32-bit libmount for Steam runtime

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/u/util-linux/libmount1_2.41-5_i386.deb"
file_size=224712
file_md5=4b9bb1384591191816546f0748684076
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libmount.so.1* "$target"/lib32/ || Die "Failed copying 32-bit libmount.so.1."
}

