#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/z/zlib/zlib1g_1.2.13.dfsg-1_i386.deb"
file_size=82644
file_md5=0348a522330b4537fd3e892f3690ec74
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a lib/i386-linux-gnu/libz.so.1* "$target"/lib32/ || Die "Failed copying 32-bit zlib."
}
