#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/m/mpg123/libmpg123-0_1.31.2-1+deb12u1_i386.deb"
file_size=149604
file_md5=464e95d1e58aea350813b5faaf7ff08d
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libmpg123.so.0* "$target"/lib32/ || Die "Failed copying 32-bit mpg123."
}
