#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/g/gdk-pixbuf/libgdk-pixbuf-2.0-0_2.42.10+dfsg-1+deb12u4_i386.deb"
file_size=147856
file_md5=a4ed6ccac0e982de34a54fc56ca20675
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libgdk_pixbuf-2.0.so.0* "$target"/lib32/ || Die "Failed copying 32-bit gdk-pixbuf."
}
