#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/t/tiff/libtiff6_4.5.0-6+deb12u4_i386.deb"
file_size=332268
file_md5=f5c11af71aeb62583faa9c8c830d18fb
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libtiff.so.6* "$target"/lib32/ || Die "Failed copying 32-bit libtiff."
}
