#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/g/gnutls28/libgnutls30_3.7.9-2+deb12u7_i386.deb"
file_size=1409032
file_md5=67a713614c10dbe0c9fb031387a8a0ff
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libgnutls.so.30* "$target"/lib32/ || Die "Failed copying 32-bit GnuTLS."
}
