#!/bin/bash

# 32-bit Xcursor extracted from Debian i386 packages for Steam/Wine gaming.

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/libx/libxcursor/libxcursor1_1.2.3-1_i386.deb"
file_size=41240
file_md5=26d343f2fcaeeb25318a703dfc33cfc9
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libXcursor.so.1* "$target"/lib32/ || Die "Failed copying 32-bit libXcursor."
}
