#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/h/harfbuzz/libharfbuzz0b_6.0.0+dfsg-3_i386.deb"
file_size=1965524
file_md5=5916848bde859b8d0ec1388139b2c192
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libharfbuzz.so.0* "$target"/lib32/ || Die "Failed copying 32-bit harfbuzz."
}
