#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/f/fontconfig/libfontconfig1_2.13.1-4.2_i386.deb"
file_size=357536
file_md5=1fbeecc587ea6e3436287cd92c2b2496
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libfontconfig.so.1* "$target"/lib32/ || Die "Failed copying 32-bit Fontconfig."
}
