#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/libg/libgsm/libgsm1_1.0.22-1_i386.deb"
file_size=31380
file_md5=6d383d514e89f720d8bed8a450912500
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libgsm.so.1* "$target"/lib32/ || Die "Failed copying 32-bit gsm."
}
