#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/f/freetype/libfreetype6_2.12.1+dfsg-5+deb12u4_i386.deb"
file_size=409064
file_md5=8ec10eb36ceca821e1c77237a8260535
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libfreetype.so.6* "$target"/lib32/ || Die "Failed copying 32-bit FreeType."
}
