#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/libo/libogg/libogg0_1.3.5-3_i386.deb"
file_size=24112
file_md5=6250205fef3bc59c414e54de928ab020
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libogg.so.0* "$target"/lib32/ || Die "Failed copying 32-bit libogg."
}
