#!/bin/bash

compile_version=017-GIT
url="https://deb.debian.org/debian/pool/main/libp/libpng1.6/libpng16-16_1.6.39-2+deb12u5_i386.deb"
file_size=284712
file_md5=2091061f11213c052e9b544bb2f21bdb
recipe_type=manifest
uncompress=no

pre_install() {
    local deb="$compileArchivesDir/$(basename $url)"
    Log_Normal "Unpacking ${deb}"
    ar p "$deb" data.tar.xz | tar xJf -
}

do_install() {
    mkdir -p "$target"/lib32
    cp -a usr/lib/i386-linux-gnu/libpng16.so* "$target"/lib32/ || Die "Failed copying 32-bit libpng."
}
